/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ubutun_ubutun在ubutun里完美运行ffmpeg"
#endif /* AVUTIL_FFVERSION_H */
